global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: web_app
    static_configs:
      - targets: ["${web_private_ip}:8000"]

  - job_name: web_node
    static_configs:
      - targets: ["${web_private_ip}:9100"]

  - job_name: db_mysql
    static_configs:
      - targets: ["${db_private_ip}:9104"]

  - job_name: db_node
    static_configs:
      - targets: ["${db_private_ip}:9100"]
